version: "3.9"
services:
  keycloak:
    image: quay.io/keycloak/keycloak:20.0.0
    container_name: keycloak
    command: start-dev
    environment:
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - "8080:8080"
    volumes:
      - ./data/keycloak:/opt/keycloak/data
  db:
    image: mysql:8.0
    container_name: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: saml
      MYSQL_USER: user
      MYSQL_PASSWORD: my_password
    volumes:
      - ./data/mysql:/var/lib/mysql
    ports:
      - "3306:3306"
